#!/bin/bash

# Do not edit this file!

# To change authToken and owner id:

echo "Creating config.json..."
cd /home/shell-bot
cat > config.json << EOF
{
    "authToken": "5598853189:AAF0pnW0yBi0QsWvO6K7Fp4g4Tm1-cZcfSU",
    "owner": 1092778891
}
EOF
echo "Done."

echo "Starting Bot..."
node server
