#!/bin/bash

# Do not edit this file!

# To change authToken and owner id:

echo "Creating config.json..."
cd /home/shell-bot
cat > config.json << EOF
{
    "authToken": "$BOT_TOKEN",
    "owner": $Pemilik
}
EOF
echo "Done."

echo "Starting Bot..."
node server
